imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@UserBundle/Resources/config/services.yml" }
    - { resource: "@CoreBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    app.path.product_images: /uploads/images

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'bootstrap_3_layout.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

# EasyAdmin Configuration
# https://symfony.com/doc/current/bundles/EasyAdminBundle/index.html
easy_admin:
    entities:
        Adverts:
            class: CoreBundle\Entity\Adverts
            label: 'Chevaux'
            list:
                title: "Liste des chevaux"
            form:
                fields:
                    - { type: 'group', label: 'Informations "à l''adoption / à parrainer"', help: "Informations visible quand le cheval est à l'adoption ou à parrainer", css_class: 'col-sm-6' }
                    - { property: 'name', label: "Nom" }
                    - { property: 'category', label: "Catégories" }
                    - { property: 'descriptionInitial', label: "Description (à l'adoption / à parrainer)", type: 'ckeditor' }
                    - { property: 'images', label: 'Images', css_class: 'js-krajee_file_input' }
                    - { property: 'dateCreation', label: 'Date de création', type_options: { widget: 'single_text' }, css_class: 'js-datepicker' }
                    - { property: 'published', label: 'Publiée' }
                    - { type: 'group', label: 'Informations "adopté / parrainé"', help: 'Informations visible une fois le cheval adopté ou parrainé', css_class: 'col-sm-6' }
                    - { property: 'descriptionComplete', label: "Description (adopté/parrainé)", type: 'ckeditor' }
                    - { property: 'dateAdopted', label: "Date d'adoption", type_options: { widget: 'single_text' }, css_class: 'js-datepicker' }
                    - { type: 'group', label: 'Informations "décédé"', help: 'Informations visible si le cheval décédé', css_class: 'col-sm-6' }
                    - { property: 'descriptionDeceased', label: 'Description (décédé)', type: 'ckeditor' }
            new:
                title: "Ajouter un cheval"
                form_options: { validation_groups: ['Default', 'Adverts'] }
            edit:
                title: "Éditer un cheval"
                fields:
                    - { type: 'group', label: 'Informations "à l''adoption / à parrainer"', help: "Informations visible quand le cheval est à l'adoption ou à parrainer", css_class: 'col-sm-6' }
                    - { property: 'name', label: "Nom" }
                    - { property: 'category', label: "Catégories" }
                    - { property: 'descriptionInitial', label: "Description (à l'adoption / à parrainer)", type: 'ckeditor' }
                    - { property: 'images', label: 'Images', css_class: 'js-krajee_file_input' }
                    - { property: 'dateCreation', label: 'Date de création', type_options: { widget: 'single_text' }, css_class: 'js-datepicker' }
                    - { property: 'published', label: 'Publiée' }
                    - { type: 'group', label: 'Informations "adopté / parrainé"', help: 'Informations visible une fois le cheval adopté ou parrainé', css_class: 'col-sm-6' }
                    - { property: 'descriptionComplete', label: "Description (adopté/parrainé)", type: 'ckeditor' }
                    - { property: 'dateAdopted', label: "Date d'adoption", type_options: { widget: 'single_text' }, css_class: 'js-datepicker' }
                    - { type: 'group', label: 'Informations "décédé"', help: 'Informations visible si le cheval décédé', css_class: 'col-sm-6' }
                    - { property: 'descriptionDeceased', label: 'Description (décédé)', type: 'ckeditor' }
            new:
                title: "Ajouter un cheval"
                form_options: { validation_groups: ['Default', 'Adverts'] }
            edit:
                title: "Éditer un cheval"
                fields:
                    - '-dateCreation'
                form_options: { validation_groups: ['Default', 'Adverts'] }
        Categories:
            class: CoreBundle\Entity\Categories
            label: 'Catégories'
            list:
                title: "Liste des catégories"
    site_name: 'DS&DC - Admin'
    design:
        brand_color: '#994DB6'

# Vich uploader
# https://symfony.com/doc/current/bundles/EasyAdminBundle/integration/vichuploaderbundle.html
vich_uploader:
    db_driver: orm
    mappings:
        product_images:
            uri_prefix: '%app.path.product_images%'
            upload_destination: '%kernel.root_dir%/../web/uploads/images'
