advert:
    resource: "@AdvertBundle/Resources/config/routing.yml"
    prefix:   /

core:
    resource: "@CoreBundle/Controller/"
    type: annotation

user:
    resource: "@UserBundle/Controller/"
    type: annotation
